# Generated by Django 2.2 on 2020-03-26 09:56

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_html',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='正文'),
        ),
    ]
